# Generated by Django 4.2.11 on 2024-04-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_pattern_pattern_pdf_pattern_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='description',
            field=models.CharField(default='description', max_length=200),
        ),
    ]
