# Generated by Django 4.2.11 on 2024-04-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_pattern_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='gauge',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='needle_size',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='yarn',
            field=models.CharField(default='yarn', max_length=100),
        ),
    ]
